### ISSUE TITLE
Shell showing as SH even when using Bash/ZSH/Fish etc

### ISSUE THREAD

**Issue by 0xBraeden** [Itsnexn/meowfetch#2]
Meowfetch only displaying SH as the system shell even when BASH, ZSH, FISH, etc are in use.

System Details -

EndeavourOS - Arch 5.19.2-arch1-1 Kernel
ZSH Shell (Do have Bash and FISH installed)

Steps to replicate -
Run `meowfetch` with the `shell` option added to `widgets =`
Produces the following for detected shell -
![image](https://user-images.githubusercontent.com/111668567/185820949-301276ff-f7a3-4426-97d7-d15c8cda4671.png)
Run `meowfetch`using `env SHELL=<shellofchoice> meowfetch`
Completes with detected shell as `sh`
![image](https://user-images.githubusercontent.com/111668567/185821320-7b3a47ba-c3f1-4d53-a577-05fdd2cf8985.png)

**Comment by faynopi** [comment]
Sorry for the inconvenience. I'll look into it as soon as possible.

It appears that I made a mistake in:
https://github.com/Itsnexn/meowfetch/blob/98d1968f07151157f1156ceb6250ace04e9739c0/internals/widgets/shell.go#L27
by setting the return value to `sh` after checking the environment variable... :^)

**Comment by faynopi** [comment]
This should fix it for the time being :)
