### ISSUE TITLE
Crash when trying to show zsh shell version via shell_version

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [Itsnexn/meowfetch#8]
![image](https://user-images.githubusercontent.com/13170204/190862748-ee0b9454-3edb-49f3-986f-b4a29027d5e6.png)
```
goroutine 1 [running]:
meowfetch/configs.ParseConfig()
	/home/pm/Documents/meowfetch/configs/config.go:44 +0x4e
main.main()
	/home/pm/Documents/meowfetch/main.go:27 +0x2e

```
*(Ignore my shell repeating my commands, I misstyped the zsh command version and created a second zsh instance in the process)*

**Comment by faynopi** [comment]
The error message indicates that the error is within your configuration file. and your file is not a valid [TOML](https://toml.io/en/) file.

but it seems like you're right the shell version doesn't work properly. I'll fix this issue with a quick patch soon.

**Comment by faynopi** [comment]
Closing for now.

**Comment by PoorPocketsMcNewHold** [comment]
Indeed. It was myself you incorrectly assumed the `shell_version` was a way to manually set a specific shell for the `shell` widget, instead as a true/false setting. Should have expected it with the default false setting. Works with #10.
